### PR TITLE
Add endpoints

### PR DESCRIPTION
**Pull request by mwarkentin**
New endpoint methods:
- `list_fim_policies`
- `get_fim_policy`
- `list_fim_baselines`
- `get_fim_baseline`
- `list_servers`
- `rebaseline_baseline`

### CODE REVIEW

**Comment by mwarkentin** [comment]
@rgooler Hey, I'm back again with some more additions - let me know if there's any changes you'd like to see.

**Comment by nduthoit** [comment]
+1 to include these endpoints

**Comment by mwarkentin** [comment]
Hey @rgooler - it looks like the client is totally broken now - CP removed the `scope` attribute from their token response.

My latest commit fixes it.

Not sure if you're still maintaining this anymore or not.

**Comment by rgooler** [comment]
I'm not really maintaining this anymore, as cloudpassage has an official python API.

**Pull request closed without merging**
